In [28]:
import numpy as np

In [29]:
print("NumPy version:", np.__version__)

NumPy version: 1.26.4


In [30]:
np?

In [31]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [32]:
np.full((3, 5), 3.14, dtype= 'int')

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [33]:
np.linspace(10, 5, 3)

array([10. ,  7.5,  5. ])

In [34]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
n = np.empty(5)

In [36]:
np.empty?

In [37]:
n.dtype

dtype('float64')

In [38]:
x = np.random.randint(20, size=(3,3))

In [39]:
x

array([[13, 16,  1],
       [ 5, 12,  2],
       [18, 17, 10]])

In [40]:
x[0][0]

13

In [41]:
x[1][2]

2

In [42]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [43]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [44]:
np.split?

In [45]:
np.ndarray

numpy.ndarray

In [46]:
grid = np.arange(24).reshape((4, 6))
grid

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [49]:
a, b =np.vsplit(grid,[1])

In [26]:
print(a)
print(b)

[[ 0]
 [ 6]
 [12]
 [18]]
[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [13 14 15 16 17]
 [19 20 21 22 23]]


In [51]:
m= np.arange(1,4).reshape(3,1)
u = np.arange(3)

In [52]:
m

array([[1],
       [2],
       [3]])

In [53]:
u

array([0, 1, 2])

In [54]:
u+m

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [55]:
x =np.random.random((10,3))
x

array([[0.70558171, 0.41834633, 0.36426117],
       [0.732085  , 0.85580151, 0.85883601],
       [0.0323916 , 0.44900097, 0.71422243],
       [0.69129373, 0.619412  , 0.52141584],
       [0.83289824, 0.1236178 , 0.1729459 ],
       [0.68132568, 0.54920877, 0.11487639],
       [0.58586074, 0.01747324, 0.57712123],
       [0.77686923, 0.35955731, 0.68222862],
       [0.18156877, 0.24260213, 0.78510439],
       [0.85561126, 0.9157866 , 0.42436812]])

In [59]:
mean = x.mean(1)
mean

array([0.49606307, 0.81557417, 0.39853833, 0.61070719, 0.37648731,
       0.44847028, 0.39348507, 0.60621839, 0.40309176, 0.73192199])

In [60]:
# x and y have 50 steps from 0 to 5
x = np.linspace(0, 5, 50)
y = np.linspace(0, 5, 50)[:, np.newaxis]

z = np.sin(x) ** 10 + np.cos(10 + y * x) * np.cos(x)

In [61]:
x , y , z

(array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
        0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
        1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
        1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
        2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
        2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
        3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
        3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
        4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
        4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ]),
 array([[0.        ],
        [0.10204082],
        [0.20408163],
        [0.30612245],
        [0.40816327],
        [0.51020408],
        [0.6122449 ],
        [0.71428571],
        [0.81632653],
        [0.91836735],
        [1.02040816],
        [1.12244898],
        [1.2244898 ],
        [1.32653061],
        [1

In [62]:
z

array([[-0.83907153, -0.83470697, -0.8216586 , ...,  0.8956708 ,
         0.68617261,  0.41940746],
       [-0.83907153, -0.82902677, -0.8103873 , ...,  0.92522407,
         0.75321348,  0.52508175],
       [-0.83907153, -0.82325668, -0.79876457, ...,  0.96427357,
         0.84172689,  0.66446403],
       ...,
       [-0.83907153, -0.48233077, -0.01646558, ...,  0.96449925,
         0.75196531,  0.41982581],
       [-0.83907153, -0.47324558,  0.00392612, ...,  0.92542163,
         0.68540362,  0.37440839],
       [-0.83907153, -0.46410908,  0.02431613, ...,  0.89579384,
         0.65690314,  0.40107702]])

In [69]:
a = np.zeros(6)[:,np.newaxis]
a

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [72]:
b=a[:,np.newaxis]
b

array([[[0.]],

       [[0.]],

       [[0.]],

       [[0.]],

       [[0.]],

       [[0.]]])

In [75]:
b.ndim

3

In [76]:
b.shape

(6, 1, 1)